### PR TITLE
Pair programming mobile portfolio review

### PR DESCRIPTION
**Pull request by bollavilla**
readme has been updated wit authors
Mobile version has been completed

### CODE REVIEW

**Review by Kamba56 — COMMENTED** [review]
Hi @samif1, @bollavilla 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that **Does not have commits from the two coding partners. **You are expected to work on this project together and commit in each others repositories. Kindly do that please.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by bollavilla** [comment]
@Kamba56 please I don't really get the way we have to do it. Do we create a repository for the peer group and copy the pull link. Can you please brief me on what to do

**Comment by Kamba56** [comment]
Hi @bollavilla, you should add your coding partner as a collaborator to your repo and make sure your partner also commits to the branch you are working on.
The commit history will be checked by the code reviewer to make sure that both coding partners made some contribution to the work.

**Review by topeogunleye — COMMENTED** [review]
Hi @bollavilla, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a pair programming project with no contributions from your partner.  Kindly report any issue you had with your partner to the student's success team and they'll permit you to work solo or look for a suitable partner, then include the report from student success in your PR description.

## Invalid Code Review Request ⚠️

- You have submitted a project, that does not have running linters. Please ensure that your linters are running before you submit for review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Pull request closed without merging**
